FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY frontend/package.json frontend/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY frontend ./

EXPOSE 4200
